### ISSUE TITLE
Practica11

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-proyecto-contrato-inteligente-equipo-m#1]
[Practica11_Gestion_De_Proyectos.pdf](https://github.com/user-attachments/files/18067443/Practica11_Gestion_De_Proyectos.pdf)

**Comment by Irvingzr16** [comment]
**Portada y los escudos** institucionales: **25 puntos**
**Objetivos** de la práctica, bien desarrollados: **25 puntos**
**Procedimiento** bien redactado y detallado: **25 puntos**
Muestra **resultados y conclusiones** cumpliendo con los criterios establecidos: **25 puntos**

Puntaje total **100% = 50 puntos**

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
